// Sensor key mappings adapted from exelban/Stats (MIT); see THIRD_PARTY_NOTICES.md.
import Foundation

public enum SensorCatalog {
    public static func description(key: String, chip: String) -> (String, SensorReading.Group) {
        let families: [(String, [(String, String, SensorReading.Group)])] = [
            ("Apple M1", [
                ("Tp09", "CPU efficiency core 1", .cpu),
                ("Tp0T", "CPU efficiency core 2", .cpu),
                ("Tp01", "CPU performance core 1", .cpu),
                ("Tp05", "CPU performance core 2", .cpu),
                ("Tp0D", "CPU performance core 3", .cpu),
                ("Tp0H", "CPU performance core 4", .cpu),
                ("Tp0L", "CPU performance core 5", .cpu),
                ("Tp0P", "CPU performance core 6", .cpu),
                ("Tp0X", "CPU performance core 7", .cpu),
                ("Tp0b", "CPU performance core 8", .cpu),
                ("Tg05", "GPU 1", .gpu),
                ("Tg0D", "GPU 2", .gpu),
                ("Tg0L", "GPU 3", .gpu),
                ("Tg0T", "GPU 4", .gpu),
            ]),
            ("Apple M2", [
                ("Tp1h", "CPU efficiency core 1", .cpu),
                ("Tp1t", "CPU efficiency core 2", .cpu),
                ("Tp1p", "CPU efficiency core 3", .cpu),
                ("Tp1l", "CPU efficiency core 4", .cpu),
                ("Tp01", "CPU performance core 1", .cpu),
                ("Tp05", "CPU performance core 2", .cpu),
                ("Tp09", "CPU performance core 3", .cpu),
                ("Tp0D", "CPU performance core 4", .cpu),
                ("Tp0X", "CPU performance core 5", .cpu),
                ("Tp0b", "CPU performance core 6", .cpu),
                ("Tp0f", "CPU performance core 7", .cpu),
                ("Tp0j", "CPU performance core 8", .cpu),
                ("Tg0f", "GPU 1", .gpu),
                ("Tg0j", "GPU 2", .gpu),
            ]),
            ("Apple M3", [
                ("Te05", "CPU efficiency core 1", .cpu),
                ("Te0L", "CPU efficiency core 2", .cpu),
                ("Te0P", "CPU efficiency core 3", .cpu),
                ("Te0S", "CPU efficiency core 4", .cpu),
                ("Tf04", "CPU performance core 1", .cpu),
                ("Tf09", "CPU performance core 2", .cpu),
                ("Tf0A", "CPU performance core 3", .cpu),
                ("Tf0B", "CPU performance core 4", .cpu),
                ("Tf0D", "CPU performance core 5", .cpu),
                ("Tf0E", "CPU performance core 6", .cpu),
                ("Tf44", "CPU performance core 7", .cpu),
                ("Tf49", "CPU performance core 8", .cpu),
                ("Tf4A", "CPU performance core 9", .cpu),
                ("Tf4B", "CPU performance core 10", .cpu),
                ("Tf4D", "CPU performance core 11", .cpu),
                ("Tf4E", "CPU performance core 12", .cpu),
                ("Tf14", "GPU 1", .gpu),
                ("Tf18", "GPU 2", .gpu),
                ("Tf19", "GPU 3", .gpu),
                ("Tf1A", "GPU 4", .gpu),
                ("Tf24", "GPU 5", .gpu),
                ("Tf28", "GPU 6", .gpu),
                ("Tf29", "GPU 7", .gpu),
                ("Tf2A", "GPU 8", .gpu),
            ]),
            ("Apple M4", [
                ("Te05", "CPU efficiency core 1", .cpu),
                ("Te0S", "CPU efficiency core 2", .cpu),
                ("Te09", "CPU efficiency core 3", .cpu),
                ("Te0H", "CPU efficiency core 4", .cpu),
                ("Tp01", "CPU performance core 1", .cpu),
                ("Tp05", "CPU performance core 2", .cpu),
                ("Tp09", "CPU performance core 3", .cpu),
                ("Tp0D", "CPU performance core 4", .cpu),
                ("Tp0V", "CPU performance core 5", .cpu),
                ("Tp0Y", "CPU performance core 6", .cpu),
                ("Tp0b", "CPU performance core 7", .cpu),
                ("Tp0e", "CPU performance core 8", .cpu),
                ("Tg0K", "GPU 3", .gpu),
                ("Tg0L", "GPU 4", .gpu),
                ("Tg0d", "GPU 5", .gpu),
                ("Tg0e", "GPU 6", .gpu),
                ("Tg0j", "GPU 7", .gpu),
                ("Tg0k", "GPU 8", .gpu),
                ("Tg0G", "GPU 1", .gpu),
                ("Tg0H", "GPU 2", .gpu),
                ("Tg1U", "GPU 1", .gpu),
                ("Tg1k", "GPU 2", .gpu),
            ]),
            ("Apple M5", [
                ("Tp00", "CPU super core 1", .cpu),
                ("Tp04", "CPU super core 2", .cpu),
                ("Tp08", "CPU super core 3", .cpu),
                ("Tp0C", "CPU super core 4", .cpu),
                ("Tp0G", "CPU super core 5", .cpu),
                ("Tp0K", "CPU super core 6", .cpu),
                ("Tp0O", "CPU performance core 1", .cpu),
                ("Tp0R", "CPU performance core 2", .cpu),
                ("Tp0U", "CPU performance core 3", .cpu),
                ("Tp0X", "CPU performance core 4", .cpu),
                ("Tp0a", "CPU performance core 5", .cpu),
                ("Tp0d", "CPU performance core 6", .cpu),
                ("Tp0g", "CPU performance core 7", .cpu),
                ("Tp0j", "CPU performance core 8", .cpu),
                ("Tp0m", "CPU performance core 9", .cpu),
                ("Tp0p", "CPU performance core 10", .cpu),
                ("Tp0u", "CPU performance core 11", .cpu),
                ("Tp0y", "CPU performance core 12", .cpu),
                ("Tg0U", "GPU 1", .gpu),
                ("Tg0X", "GPU 2", .gpu),
                ("Tg0d", "GPU 3", .gpu),
                ("Tg0g", "GPU 4", .gpu),
                ("Tg0j", "GPU 5", .gpu),
                ("Tg1Y", "GPU 6", .gpu),
                ("Tg1c", "GPU 7", .gpu),
                ("Tg1g", "GPU 8", .gpu),
            ]),
        ]
        if let family = families.first(where: { chip.hasPrefix($0.0) }),
           let sensor = family.1.first(where: { $0.0 == key }) { return (sensor.1, sensor.2) }
        if !chip.hasPrefix("Apple") {
            if key == "TC0D" || key == "TCAD" { return (key == "TCAD" ? "CPU package" : "CPU diode", .cpu) }
            if key == "TG0D" || key == "TGDD" || key == "TCGC" { return ("GPU diode · " + key, .gpu) }
        }
        if key.hasPrefix("F"), key.hasSuffix("Ac"), let index = Int(key.dropFirst().dropLast(2)) { return ("Fan \(index + 1)", .fan) }
        let common: [String: (String, SensorReading.Group)] = [
            "TB0T": ("Battery pack", .battery), "TB1T": ("Battery 1", .battery), "TB2T": ("Battery 2", .battery),
            "TH0x": ("SSD / NAND", .other), "TaLP": ("Airflow left", .other), "TaRF": ("Airflow right", .other),
            "Tm0P": ("Mainboard", .other), "TW0P": ("Wi-Fi", .other), "TL0P": ("Display", .other)
        ]
        return common[key] ?? (key, .other)
    }
}
